### ISSUE TITLE
SEC001/VID005: Build the Conventional Buy and Hold Strategy

### ISSUE THREAD

**Issue by narun4sk** [PacktPublishing/Machine-Learning-for-Algorithmic-Trading-Bots-with-Python#1]
Source code does not work out of the box:
```
$ git branch 
* SEC001_VID005_Build_the_Conventional_Buy_and_Hold_Strategy
  SEC002_VID003_Plug_in_Random_Forests_Implementation_into_your_Bot
  SEC003_VID003_Implement_Statistical_Auto_Correlation_Strategy
  SEC005_VID002_Implement_Scalpers_Trading_Strategy
  SEC006_VID002_Implement_Value_at_Risk_Backtest
  SEC006_VID004_Implement_VaR_using_SVR
  master
```
```
$ zipline bundles
csvdir <no ingestions>
quandl 2020-01-05 16:35:57.206839
quantopian-quandl 2020-01-05 16:35:34.653587
```
```
$ python3 main.py 
*** PackPub - Hands-on Machine Learning for Algorithmic Trading Bots ***
*** SEC001/VID005: Build the Conventional Buy and Hold Strategy ***
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    main()
  File "main.py", line 10, in main
    perf = run_strategy("buy_and_hold")
  File "/home/jupyter/nb/Machine.Learning.for.Algorithmic.Trading.Bots/packtpub-src/strategies/run_zipline.py", line 64, in run_strategy
    **merge({'capital_base': 1e7}, mod._test_args())
  File "/home/jupyter/env/lib/python3.5/site-packages/zipline/utils/run_algo.py", line 430, in run_algorithm
    blotter=blotter,
  File "/home/jupyter/env/lib/python3.5/site-packages/zipline/utils/run_algo.py", line 159, in _run
    trading_days=trading_calendar.schedule[start:end].index,
  File "/home/jupyter/env/lib/python3.5/site-packages/zipline/finance/trading.py", line 103, in __init__
    self.bm_symbol,
  File "/home/jupyter/env/lib/python3.5/site-packages/zipline/data/loader.py", line 149, in load_market_data
    environ,
  File "/home/jupyter/env/lib/python3.5/site-packages/zipline/data/loader.py", line 216, in ensure_benchmark_data
    data = get_benchmark_returns(symbol)
  File "/home/jupyter/env/lib/python3.5/site-packages/zipline/data/benchmarks.py", line 35, in get_benchmark_returns
    data = r.json()
  File "/home/jupyter/env/lib/python3.5/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by narun4sk** [comment]
It seems it's `zipline` related issue, as at the moment it's unable to download the benchmark data from the IEX Trading...
